##############################################################################################
# Author: Weijia Fu
# Purpose: Comparing survival estimates generated by new model to CONCORD survival estimates 
# Date: 04/27/2022
##############################################################################################
###### load packages and define paths ######
library(data.table)
library(ggplot2)
library(dplyr)
source("/ihme/cc_resources/libraries/current/r/get_location_metadata.R")
source("/ihme/cc_resources/libraries/current/r/get_outputs.R")
source("/ihme/cc_resources/libraries/current/r/get_ids.R")
pathToConcordData <- "/home/j/temp/registry/cancer/keep_post_wipe/temp_jonathan/survival2019/CONCORD/"

###### define functions #######
## function to age-standardize (group 1) the survival draws (for comparison to CONCORD estimates)
## this is for the cancers using standard 1 (esophageal, stomach, colorectal, liver, pancreas,
## lung, breast, ovarian, prostate, leukemia(adult))
getAgeStd1 <- function(inputData){
  ageStd <- data.frame()
  tempAgeStd <- inputData
  
  tempAgeStd$ageStdScalar[tempAgeStd$age_group_id == 8 ] <- 0.0016
  tempAgeStd$ageStdScalar[tempAgeStd$age_group_id == 9 ] <- 0.0021
  tempAgeStd$ageStdScalar[tempAgeStd$age_group_id == 10] <- 0.0042
  tempAgeStd$ageStdScalar[tempAgeStd$age_group_id == 11] <- 0.0084
  tempAgeStd$ageStdScalar[tempAgeStd$age_group_id == 12] <- 0.0188
  tempAgeStd$ageStdScalar[tempAgeStd$age_group_id == 13] <- 0.0349
  tempAgeStd$ageStdScalar[tempAgeStd$age_group_id == 14] <- 0.0491
  tempAgeStd$ageStdScalar[tempAgeStd$age_group_id == 15] <- 0.0709
  tempAgeStd$ageStdScalar[tempAgeStd$age_group_id == 16] <- 0.0964
  tempAgeStd$ageStdScalar[tempAgeStd$age_group_id == 17] <- 0.1336
  tempAgeStd$ageStdScalar[tempAgeStd$age_group_id == 18] <- 0.1423
  tempAgeStd$ageStdScalar[tempAgeStd$age_group_id == 19] <- 0.1477
  tempAgeStd$ageStdScalar[tempAgeStd$age_group_id == 20] <- 0.1413
  tempAgeStd$ageStdScalar[tempAgeStd$age_group_id == 30] <- 0.0935
  temp85plus <- 0.0552
  tempAgeStd$scaledVal <- tempAgeStd$meanSurv * tempAgeStd$ageStdScalar   #multiply scalars
  
  for (location in unique(inputData$location_id)) {
    tempAgeStdloc <-tempAgeStd[location_id == location]
    for(sex in c(1, 2)){
      tempAgeStdSex <- tempAgeStdloc[sex_id == sex, ]
      for(year in c(2002, 2007, 2012)){
        tempAgeStdYear <- tempAgeStdSex[year_id == year, ]
        # CONCORD goes to 85+, GBD to 95+; need to combine these three:
        tempOlderAge <- mean(c(tempAgeStdYear$meanSurv[tempAgeStdYear$age_group_id==31],
                               tempAgeStdYear$meanSurv[tempAgeStdYear$age_group_id==32],
                               tempAgeStdYear$meanSurv[tempAgeStdYear$age_group_id==235]))
        tempAgeStdYear$scaledVal[tempAgeStdYear$age_group_id == 31] <- tempOlderAge * temp85plus #use 31 arbitrarily
        tempAgeStdYear$ageStdSurv <- sum(tempAgeStdYear$scaledVal, na.rm=T)   #get total age-standardized value
        tempAgeStdReduced <- tempAgeStdYear[age_group_id==15, ]  #keep a single row per sex/year (15 arbitrary)
        ageStd <- rbind(ageStd, tempAgeStdReduced) #add this row and loop again
      }
    }
  }
  return(ageStd)
}

## function to age-standardize (group 2) the survival draws (for comparison to CONCORD estimates)
## this is for the cancers using standard 2 (cervical, melanoma, brain(adult))
getAgeStd2 <- function(inputData){
  ageStd <- data.frame()
  tempAgeStd <- inputData
  
  tempAgeStd$ageStdScalar[tempAgeStd$age_group_id == 8 ] <- 0.0113
  tempAgeStd$ageStdScalar[tempAgeStd$age_group_id == 9 ] <- 0.0201
  tempAgeStd$ageStdScalar[tempAgeStd$age_group_id == 10] <- 0.0374
  tempAgeStd$ageStdScalar[tempAgeStd$age_group_id == 11] <- 0.0575
  tempAgeStd$ageStdScalar[tempAgeStd$age_group_id == 12] <- 0.0754
  tempAgeStd$ageStdScalar[tempAgeStd$age_group_id == 13] <- 0.0782
  tempAgeStd$ageStdScalar[tempAgeStd$age_group_id == 14] <- 0.0828
  tempAgeStd$ageStdScalar[tempAgeStd$age_group_id == 15] <- 0.0872
  tempAgeStd$ageStdScalar[tempAgeStd$age_group_id == 16] <- 0.0990
  tempAgeStd$ageStdScalar[tempAgeStd$age_group_id == 17] <- 0.1110
  tempAgeStd$ageStdScalar[tempAgeStd$age_group_id == 18] <- 0.1100
  tempAgeStd$ageStdScalar[tempAgeStd$age_group_id == 19] <- 0.0900
  tempAgeStd$ageStdScalar[tempAgeStd$age_group_id == 20] <- 0.0725
  tempAgeStd$ageStdScalar[tempAgeStd$age_group_id == 30] <- 0.0412
  temp85plus <- 0.0263
  tempAgeStd$scaledVal <- tempAgeStd$meanSurv * tempAgeStd$ageStdScalar   #multiply scalars
  
  for (location in unique(inputData$location_id)) {
    tempAgeStdloc <-tempAgeStd[location_id == location]
    for(sex in c(1, 2)){
      tempAgeStdSex <- tempAgeStdloc[sex_id == sex, ]
      for(year in c(2002, 2007, 2012)){
        tempAgeStdYear <- tempAgeStdSex[year_id == year, ]
        # CONCORD goes to 85+, GBD to 95+; need to combine these three:
        tempOlderAge <- mean(c(tempAgeStdYear$meanSurv[tempAgeStdYear$age_group_id==31],
                               tempAgeStdYear$meanSurv[tempAgeStdYear$age_group_id==32],
                               tempAgeStdYear$meanSurv[tempAgeStdYear$age_group_id==235]))
        tempAgeStdYear$scaledVal[tempAgeStdYear$age_group_id == 31] <- tempOlderAge * temp85plus #use 31 arbitrarily
        tempAgeStdYear$ageStdSurv <- sum(tempAgeStdYear$scaledVal, na.rm=T)   #get total age-standardized value
        tempAgeStdReduced <- tempAgeStdYear[age_group_id==15, ]  #keep a single row per sex/year (15 arbitrary)
        ageStd <- rbind(ageStd, tempAgeStdReduced) #add this row and loop again
      }
    }
  }
  return(ageStd)
}

## function to age-standardize (group 3) the survival draws (for comparison to CONCORD estimates)
## this is for the cancers using equal weighting for childhood cancers (brain(children),
## ALL(children), lymphoma(children))
getAgeStd3 <- function(inputData){
  ageStd <- data.frame()
  tempAgeStd <- inputData
  
  tempAgeStd$ageStdScalar[tempAgeStd$age_group_id == 1] <- 0.3333
  tempAgeStd$ageStdScalar[tempAgeStd$age_group_id == 6] <- 0.3333
  tempAgeStd$ageStdScalar[tempAgeStd$age_group_id == 7] <- 0.3333
  
  tempAgeStd$scaledVal <- tempAgeStd$meanSurv * tempAgeStd$ageStdScalar   #multiply scalars
  
  for(location in unique(inputData$location_id)) {
    tempAgeStdloc <-tempAgeStd[location_id == location]
    for(sex in c(1, 2)){
      tempAgeStdSex <- tempAgeStdloc[sex_id == sex, ]
      for(year in c(2002, 2007, 2012)){
        tempAgeStdYear <- tempAgeStdSex[year_id == year, ]
        tempAgeStdYear$ageStdSurv <- sum(tempAgeStdYear$scaledVal, na.rm=T)   #get total age-standardized value
        tempAgeStdReduced <- tempAgeStdYear[age_group_id==6, ]  #keep a single row per sex/year (6 arbitrary)
        ageStd <- rbind(ageStd, tempAgeStdReduced) #add this row and loop again
      }
    }
  }
  return(ageStd)
}

## function to get age-standardized GBD values (age distribution depends on cancer type)
ageStandardizeVersion <- function(tempGBDreduced, cancer){
  if(cancer %in% c("neo_melanoma", "neo_cervical")){ 
    tempGBDageStd <- getAgeStd2(tempGBDreduced)
  } else if(cancer %in% c("neo_esophageal", "neo_stomach", "neo_colorectal", "neo_liver", "neo_pancreas",
                          "neo_lung", "neo_breast", "neo_ovarian", "neo_prostate", "neo_leukemia_ml_chronic",
                          "neo_leukemia_ll_acute")){
    tempGBDageStd <- getAgeStd1(tempGBDreduced)
  } else if(cancer %in% c("neo_leukemia_ll_acute", "neo_lymphoma")){ 
    tempGBDageStd <- getAgeStd3(tempGBDreduced)
    #brain cancer is age-standardized differently in adults(1) and kids(3)
  } else if(cancer == "neo_brain"){  
    tempGBDageStd1 <- getAgeStd2(tempGBDreduced)
    tempGBDageStd1$CONCORD_name <- "brain_adult"
    tempGBDageStd2 <- getAgeStd3(tempGBDreduced)
    tempGBDageStd2$CONCORD_name <- "brain_children"
    tempGBDageStd <- rbind(tempGBDageStd1, tempGBDageStd2)
  }
  return(tempGBDageStd)
}

# get MAD (median absolute deviation)
get_mad <- function(dat) {
  mad_pre <- median(abs(dat$concord - dat$surv_pre), na.rm = TRUE)
  mad_new <- median(abs(dat$concord - dat$surv_new), na.rm = TRUE)
  return(c(mad_pre, mad_new))
}

#########################################
##Arguments
#########################################
args <- commandArgs(trailingOnly = TRUE)
cause <- args[1]

# get concord data
concord <- fread(paste0(pathToConcordData, "matched_data/", cause, "_merged.csv"))
if (cause_name == "neo_colorectal") {
  concord <- concord[CONCORD_name == "colon"]
}
concord <- concord[ , reliability := ifelse(CONCORD_index == "less_reliable", "less_reliable", "reliable")]
concord <- concord[ , c("year_id", "location_id", "sex_id", "CONCORD_NS", "CONCORD_name", "reliability")]
concord <- concord[is.na(CONCORD_NS) == FALSE]
concord <- setnames(concord, old = "CONCORD_NS", new = "concord")
locations_id <- unique(concord$location_id)

# get old survival
surv_pre <- fread(paste0("/mnt/share/cancer/survival/plots/compare_to_previous/2019_survival_previous/", cause, "_scaled_surv_2019.csv"))
surv_pre <- surv_pre[location_id %in% locations_id]
surv_pre <- setnames(surv_pre, old = "scaled_surv_mean", new = "meanSurv")
surv_pre <- ageStandardizeVersion(surv_pre, cause)
surv_pre <- surv_pre[ , c("location_id","sex_id", "year_id", "ageStdSurv")]
surv_pre <- setnames(surv_pre, old = "ageStdSurv", new = "surv_pre")

# get new survival
surv_new <- fread(paste0("/mnt/share/cancer/survival/outputs/final/", cause, "_survival_final.csv"))
surv_new <- surv_new[location_id %in% locations_id]
surv_new <- setnames(surv_new, old = "rel_survival", new = "meanSurv")
surv_new <- ageStandardizeVersion(surv_new, cause)
surv_new <- surv_new[ , c("location_id", "sex_id", "year_id", "ageStdSurv")]
surv_new <- setnames(surv_new, old = "ageStdSurv", new = "surv_new")

#
locations_table <- get_location_metadata(22, decomp_step = "step3", gbd_round_id = 7)
locations_table_to_merge <- locations_table[, c("location_id", "location_name", "super_region_name")]

# merge concord data with old and new survival
dat_plot <- merge(concord, surv_pre, by = c("location_id", "sex_id", "year_id"))
dat_plot <- merge(dat_plot, surv_new, by = c("location_id", "sex_id", "year_id"))
dat_plot <- merge(dat_plot, locations_table_to_merge, by = "location_id")

pdf(paste0("/mnt/share/cancer/survival/plots/compare_to_CONCORD/compare_to_CONCORD_", cause, ".pdf"), width=16, height=12)
max_num <- max(dat_plot$surv_pre, dat_plot$surv_new, dat_plot$concord)
plot1 <- ggplot(data = dat_plot[sex_id == 1], aes(y = surv_pre, x = concord, color = super_region_name, shape = reliability)) + geom_point(size = 4) + 
  geom_abline(slope = 1, intercept = 0) + xlim(0, max_num) + ylim(0, max_num) + 
  scale_shape_manual(values = c(2, 19)) +
  theme(axis.text=element_text(size=20), axis.title=element_text(size=20)) + 
  ggtitle(paste0(cause, " concord comparison to previous survival male"))
print(plot1)
plot2 <- ggplot(data = dat_plot[sex_id == 1], aes(y = surv_new, x = concord, color = super_region_name, shape = reliability)) + geom_point(size = 4) + 
  geom_abline(slope = 1, intercept = 0) + xlim(0, max_num) + ylim(0, max_num) + 
  scale_shape_manual(values = c(2, 19)) +
  theme(axis.text=element_text(size=20), axis.title=element_text(size=20)) + 
  ggtitle(paste0(cause, " concord comparison to new survival male"))
print(plot2)
plot3 <- ggplot(data = dat_plot[sex_id == 2], aes(y = surv_pre, x = concord, color = super_region_name, shape = reliability)) + geom_point(size = 4) + 
  geom_abline(slope = 1, intercept = 0) + xlim(0, max_num) + ylim(0, max_num) + 
  scale_shape_manual(values = c(2, 19)) +
  theme(axis.text=element_text(size=20), axis.title=element_text(size=20)) + 
  ggtitle(paste0(cause, " concord comparison to previous survival female"))
print(plot3)
plot4 <- ggplot(data = dat_plot[sex_id == 2], aes(y = surv_new, x = concord, color = super_region_name, shape = reliability)) + geom_point(size = 4) + 
  geom_abline(slope = 1, intercept = 0) + xlim(0, max_num) + ylim(0, max_num) + 
  scale_shape_manual(values = c(2, 19)) +
  theme(axis.text=element_text(size=20), axis.title=element_text(size=20)) + 
  ggtitle(paste0(cause, " concord comparison to new survival female"))
print(plot4)
dev.off()

mad_male <- get_mad(dat_plot[sex_id == 1 & reliability == "reliable"])
mad_female <- get_mad(dat_plot[sex_id == 1 & reliability == "reliable"])

